#!/usr/bin/env node
/**
 * Bundles the Lucide icon assets in `src/icons/`:
 *
 * 1. Generates `src/icons/icons.ts` — a single module exporting every SVG as a
 *    plain string. The toolbar injects these inline (so icons inherit
 *    `currentColor`), which keeps the library framework-agnostic and lets icons
 *    render offline and over `file://` without a fetch or bundler.
 *    The generated file is committed so `tsc` always works standalone.
 * 2. Copies the raw SVG assets (plus NOTICE.md) to `dist/icons/` so they ship
 *    in the published npm package.
 *
 * Run automatically by `npm run build`. Dynamic imports are avoided entirely.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, copyFileSync, rmSync, existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const srcIcons = join(root, 'src', 'icons')
const distIcons = join(root, 'dist', 'icons')
const generated = join(srcIcons, 'icons.ts')

const ORDER = [
  'zoom-in', 'zoom-out', 'undo-2', 'rotate-ccw', 'rotate-cw',
  'refresh-ccw', 'chevron-left', 'chevron-right',
  'arrow-up', 'download', 'move-horizontal', 'scan', 'ruler', 'file', 'file-text',
  'file-stack', 'folder', 'folder-open', 'maximize', 'minimize',
  'copy', 'wrap-text', 'layout-grid', 'lock',
  'eye', 'eye-off',
]

/** Add a decorative `aria-hidden` to the root <svg> tag of a Lucide asset. */
function makeDecorative(svg) {
  return svg.replace(/<svg([\s\S]*?)>/i, (match, attrs) => {
    if (attrs.includes('aria-hidden')) return match
    const indented = attrs.endsWith('\n')
    return `<svg${attrs}${indented ? '  aria-hidden="true"\n' : 'aria-hidden="true" '}>`
  })
}

/** Guard against template-literal-breaking characters in the assets. */
function assertSafe(name, svg) {
  if (/[`$]/.test(svg)) {
    throw new Error(`icon "${name}" contains a backtick or "$" that cannot be emitted into a template literal`)
  }
}

function generate() {
  const names = readdirSync(srcIcons)
    .filter((file) => file.endsWith('.svg'))
    .map((file) => file.slice(0, -4))
    .filter((name) => ORDER.includes(name))

  const missing = ORDER.filter((name) => !names.includes(name))
  if (missing.length > 0) {
    throw new Error(`missing icon assets in ${srcIcons}: ${missing.join(', ')}`)
  }

  const entries = ORDER.map((name) => {
    const raw = readFileSync(join(srcIcons, `${name}.svg`), 'utf8').trim()
    const svg = makeDecorative(raw)
    assertSafe(name, svg)
    return `  '${name}': \`${svg}\`,` 
  })

  const header = `// This file is generated by scripts/build-icons.mjs from the Lucide SVG
// assets in src/icons/. Do not edit by hand.
//
// Icons are from Lucide (https://lucide.dev), licensed under the ISC license.
// See src/icons/NOTICE.md for the full attribution and license text.

export const ICONS = {
${entries.join('\n')}
} as const

export type IconName = keyof typeof ICONS
`
  writeFileSync(generated, header)
  console.log(`generated ${generated} (${entries.length} icons)`)
}

function copyAssets() {
  rmSync(distIcons, { recursive: true, force: true })
  mkdirSync(distIcons, { recursive: true })
  let count = 0
  for (const file of readdirSync(srcIcons)) {
    if (!file.endsWith('.svg') && file !== 'NOTICE.md') continue
    copyFileSync(join(srcIcons, file), join(distIcons, file))
    count += 1
  }
  console.log(`copied ${count} assets to ${distIcons}`)
}

if (!existsSync(srcIcons)) {
  throw new Error(`icon source directory not found: ${srcIcons}`)
}

generate()
copyAssets()