import type { PreviewOptions } from './types.js'

let customWorkerSrc: string | undefined

/**
 * Set the URL used to load the pdf.js worker module (`pdf.worker.mjs`) for
 * PDF rendering.
 *
 * The library ships with a sensible default (a version-pinned copy of the
 * worker hosted on a public CDN), so PDF previews work out of the box in any
 * bundler without extra configuration. Call this when you need to control
 * where the worker comes from:
 *
 * - self-hosted copy of `pdf.worker.min.mjs` in your own static assets, or
 * - a `Worker` URL generated by your bundler (Vite asset URL imports, Webpack
 *   asset modules, or `new URL(..., import.meta.url)`), or
 * - an offline/air-gapped environment that cannot reach a CDN.
 *
 * This is a global setting; it affects every subsequent PDF preview in the
 * page. It can be overridden per preview with {@link PreviewOptions.workerSrc}.
 */
export function setPdfWorkerSrc(url: string): void {
  customWorkerSrc = url
}

/**
 * Resolve the worker URL to use for a preview. Precedence:
 * 1. `options.workerSrc` (per-preview override)
 * 2. `setPdfWorkerSrc(...)` (global override)
 * 3. A version-pinned CDN build matching the installed pdfjs-dist, so the
 *    worker always matches the pdf.js API this package was built against.
 */
export function resolvePdfWorkerSrc(pdfjsVersion: string, options?: PreviewOptions): string {
  if (options?.workerSrc) return options.workerSrc
  if (customWorkerSrc) return customWorkerSrc
  return `https://cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjsVersion}/build/pdf.worker.min.mjs`
}